#!/usr/bin/python

quotes = ['I caught my second wife screwing my stepdad. OK? It\'s a cruel world, Walt. Grow up.',
		  'Seriously, when the going gets tough, you don\'t want a criminal lawyer... You want a \'criminal\' lawyer.',
		  'Look, let\'s start with some tough love, alright? Ready for this? Here it goes: you two suck at peddling meth. Period.',
		  'My real name\'s McGill. The Jew thing I just do for the homeboys. They all want a pipe-hitting member of the tribe, so to speak.',
		  'Hi, I\'m Saul Goodman. Did you know that you have rights? The constitution says you do! And so do I.',
		  'I\'m the guy on your speed dial right after your weed dealer!',
		  'Are you going to gum me to death?!',
		  'Walter never told me how lucky he was. Clearly his taste in women is the same as his taste in lawyers, only the very best....with just a right amount of dirty!',
		  'I wasn\'t trying to rip them off, I just wanted their business.',
		  'I just talked you down from a death sentence to 6 months probation. I\'m the best lawyer ever!',
		  'Based on the salsa stain, it could have gone a couple of ways.',
		  'Better Call Saul!',
		  'Did you not plan for this contingency? I mean, the Starship Enterprise had a self-destruct button. I\'m just saying.',
		  'There\'s no honor among thieves... except for us of course.',
		  'If you\'re committed enough, you can make any story work. I once told a woman I was Kevin Costner, and it worked because I believed it.',
		  'Conscience gets expensive, doesn\'t it?',
		  'No deal, no dice. Shot at and missed. Shit on and hit.',
		  'As to your dead guy, occupational hazard. Drug dealer getting shot? I\'m gonna go out on a limb here and say it\'s been known to happen.',
		  'You two wanna go stick your wangs in a hornets\' nest, it\'s a free country. But how come I always gotta get sloppy seconds, huh?',
		  'If I ever get anal polyps, I\'ll know what to name them.',
		  'He said he was gonna break my legs, and don\'t tell me he didn\'t mean it because he gave me the dead mackerel eyes.',
		  'Schrader\'s hard-on for you just reached Uncle Milton proportions, so have fun with that.',
		  'Some people are immune to good advice.',
		  'Say, just for the sake of argument, that the kid\'s not in the mood for a nuanced discussion of the virtues of child poisoning.',
		  'Don\'t drink and drive. But if you do, call me.',
		  'Yo, Adrian! Rocky called. He wamts his face back.',
		  'Let\'s just say I know a guy.. Who knows a guy.. Who.. Knows another guy.',
		  'Scientists love lasers!',
		  'I never should\'ve let my dojo membership run out.',
		  'Give me a call.. if you, uh, happen to know any elders.',
		  'Better safe than sorry. That\'s my motto.',
		  'Oh my God! You really are a chemistry teacher! Heh-heh...I was terrible at chemistry. I\'m more of a humanities guy.',
		  'Yeah, you do seem to have a little shit creek action going...You know, FYI, you can buy a paddle',
		  'All right, $16,000 laundered at 75 cents on the dollar, minus my fee, which is 17%, comes out to $9,960. Congratulations, you\'ve just left your family a second hand Subaru.',
	  		'Better call Saul!',
	  		'Chuck!',
	  		'S\'all good man.',
	  		'FYI, old people adore me.'
		 ];
